# frontend/Dockerfile

FROM node:20.10.0-alpine

WORKDIR /app

COPY src/ ./src
COPY package.json .
COPY package-lock.json .

RUN npm install
RUN npm run build

# Serve built files with a lightweight static server
RUN npm install -g serve

CMD ["serve", "-s", "build", "-l", "3000"]
